package com.pushnotification.messaging.telegram;

public enum TelegramMessageType {
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    NEW_REGISTRATION,
    PAYMENT_CONFIRMATION,
    PAYMENT_REFUND,
    PRO_TRIAL_EXPIRY_REMINDER,
    SMART_REPORT_READY,
    REQUEST_FORM,
    RESERVATION_CONFIRMATION,
    RESERVATION_CREATED,
    GENERIC
}
